FROM node:20-alpine
WORKDIR /laravel

# install dependencies
COPY package.json package-lock.json ./
RUN npm install

# run vite dev server with host flag for Docker access
CMD ["npm", "run", "dev", "--", "--host"]

# vite dev server port
EXPOSE 5173
