#!/bin/bash
#
# Run PHPUnit tests on the stack and return the result
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

# full directory name of the script, no matter where it is called from
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
readonly SCRIPT_NAME="${0##*/}"
readonly STACK_NAME="rmsy-me"

usage() {
  err "$(cat <<END
usage: ${SCRIPT_NAME} 
END
  )"
}

# all error messages to STDERR
err() {
  echo "-${SCRIPT_NAME}: $*" >&2
}

main() {
  local runphpunit=/var/www/tests/runphpunit

  # if the docker stack is up
  if docker stack ls | grep -q "${STACK_NAME}"; then
    local container=$(docker ps -a | grep -o "${STACK_NAME}_apache2.*")
    docker exec -t "${container}" bash -c ${runphpunit}
  # if docker-compose is up
  elif docker-compose exec -T apache2 date &> /dev/null; then
    # -T prevents an issue with shell forwarding
    docker-compose exec -T apache2 bash -c ${runphpunit} --exit-code-from \
      apache2
  else
    err "the server is not running"
    exit 1
  fi
}

main "$@"
