#!/bin/bash
#
# Run PHPUnit tests within the container and return the result
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

# full directory name of the script, no matter where it is called from
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
readonly SCRIPT_NAME="${0##*/}"

usage() {
  err "$(cat <<END
usage: ${SCRIPT_NAME} 
END
  )"
}

# all error messages to STDERR
err() {
  echo "-${SCRIPT_NAME}: $*" >&2
}

main() {
  cd /var/www/
  # creates vendor/autoload.php from composer.json
  composer dumpautoload
  
  set +e
  phpunit --bootstrap vendor/autoload.php --testdox tests --do-not-cache-result
  test_result="$?"
  set -e
  
  # cleanup
  rm -r vendor
  exit "${test_result}"
}

main "$@"
