#!/bin/bash
#
# Run PHPUnit tests within the container and return the result
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

# constants for colour display
SC="\x1B["
RED="${SC}31m"
YELLOW="${SC}33m"
NC="${SC}0m"

# constants and functions for logging
readonly SCRIPT_NAME="${BASH_SOURCE[0]##*/}"
log_prefix() {
  echo -n "[${SCRIPT_NAME}]: "
}
log() {
  log_prefix
  echo -e "${YELLOW}$@${NC}"
}
logfun() {
  log_prefix
  exec 3>&2 2>&1
  set -x
    "$@"
  { local result="$?"; set +x; } 2>/dev/null
  exec 2>&3
  return "${result}"
} 

main() {
  log "start"
  logfun cd /var/www/

  log "creating vendor/autoload.php from composer.json"
  logfun composer dumpautoload
  
  set +e
    logfun phpunit --bootstrap vendor/autoload.php --testdox tests \
      --do-not-cache-result
    local result="$?"
  set -e
  
  log "cleaning up autoload"
  logfun rm -r vendor

  log "exiting"
  exit "${result}"
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  main "$@"
fi
