#!/bin/bash
#
# Run PHPUnit tests on the currently running server and return the result
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && \
  pwd)"
. "${SCRIPT_DIR}/../../../script/lib/shared.sh"

usage() {
  die "$(cat <<END
usage: ${SCRIPT_NAME} 
END
  )"
}

main() {
  log "start"
  cd "${SCRIPT_DIR}/../../.."
  local runphpunit=/var/www/tests/runphpunit

  if is_stack_up; then
    local container="$( \
      docker ps -a \
      | grep -o "${STACK_NAME}_apache2.*" \
      | head -1 \
    )"
    set +e
      logfun docker exec -t "${container}" bash -c "${runphpunit}"
      local result="$?"
    set -e
  elif is_compose_up; then
    set +e
      logfun docker-compose \
        exec -T apache2 bash -c "${runphpunit}" --exit-code-from apache2
      local result="$?"
    set -e
  else
    die "the server is not running"
  fi

  log "exiting"
  exit "${result}"
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  main "$@"
fi
