version: '3.7'
services:
  apache2:
    container_name: apache2
    init: true
    ports:
      - "80:8080"
      - "443:8443"
    networks:
      - rmsy-me
    volumes:
      - "apache2-logs:/var/log/apache2"
      - "django-media:/var/www/media"
      - "django-migrations:/var/www/autojobgpt-django/app/migrations"
  postgres:
    container_name: postgres
    init: true
    hostname: postgres
    networks:
      - rmsy-me
    volumes:
      - "db:/var/lib/postgresql/15/main"
networks:
  rmsy-me:
    name: rmsy-me
volumes:
  db:
    external: true
  apache2-logs:
    external: true
  django-media:
    external: true
  django-migrations:
    external: true
