version: '3.7'
services:
  apache2:
    build: apache2
    volumes:
      - "secrets:/run/secrets"
      - "apache2/www:/var/www"
      - "apache2/conf:/etc/apache2"
      - "apache2/ini:/etc/php/7.3/apache2"
  postgres:
    build: postgres
    volumes:
      - "secrets:/run/secrets"
      - "postgres/conf:/etc/postgresql/11/main"
secrets:
  rmsy.me.crt:
    file: secrets/localhost.crt
  rmsy.me.key:
    file: secrets/localhost.key
  el-naggar.co.uk.crt:
    file: secrets/localhost.crt
  el-naggar.co.uk.key:
    file: secrets/localhost.key
  elnaggar.co.uk.crt:
    file: secrets/localhost.crt
  elnaggar.co.uk.key:
    file: secrets/localhost.key
  relnaggar.com.crt:
    file: secrets/localhost.crt
  relnaggar.com.key:
    file: secrets/localhost.key
  PGPASSWORD:
    file: secrets/PGPASSWORD
