version: '3.7'
services:
  apache2:
    image: rmsy-me-apache2
    build: "./apache2"
    volumes:
      - "./apache2/www:/var/www"
      - "./apache2/conf:/etc/apache2"
      - "./apache2/apache2-ini:/etc/php/7.3/apache2"
  postgres:
    image: rmsy-me-postgres
    build: "./postgres"
    volumes:
      - "./postgres/conf:/etc/postgresql/15/main"
  autojobgpt-react:
    container_name: autojobgpt-react
    init: true
    image: node:14
    networks:
      - rmsy-me
    volumes:
      - ./autojobgpt-react:/autojobgpt-react
      - ./apache2/www:/var/www
    working_dir: /autojobgpt-react
    command: ./start watch