FROM debian:13.3-slim
ENV DEBIAN_FRONTEND=noninteractive

# install apache
RUN apt-get update -y \
  && apt-get install -y --no-install-recommends \
  apache2 \
  # cleanup
  && apt autoremove -y \
  && apt clean \
  && rm -rf /var/lib/apt/lists/*

# create app user for worker process privilege dropping
RUN groupadd -r -g 999 app && useradd -r -m -g app -u 999 app \
  && mkdir -p /var/run/apache2

# enable HTTPS
RUN apt-get update -y \
  && apt-get install -y --no-install-recommends ssl-cert \
  # cleanup
  && apt autoremove -y \
  && apt clean \
  && rm -rf /var/lib/apt/lists/* \
  # fix permissions
  && chown root:app /etc/ssl/private \
  && chmod 750 /etc/ssl/private \
  && chown root:app /etc/ssl/private/ssl-cert-snakeoil.key \
  && chmod 640 /etc/ssl/private/ssl-cert-snakeoil.key

# install php-fpm
RUN apt-get update -y \
  && apt-get install -y --no-install-recommends \
  # (8.4 with debian:13.3)
  php \
  php-mbstring \
  php-xml \
  php-curl \
  php-zip \
  php-intl \
  # php-fpm
  php-fpm \
  # process supervisor
  supervisor \
  # cleanup
  && apt autoremove -y \
  && apt clean \
  && rm -rf /var/lib/apt/lists/* \
  # php-fpm runtime directory
  && mkdir -p /run/php \
  && chown app:app /run/php

# install php-sqlite3
RUN apt-get update -y \
  && apt-get install -y --no-install-recommends php-sqlite3 \
  # cleanup
  && apt autoremove -y \
  && apt clean \
  && rm -rf /var/lib/apt/lists/* \
  # database directory
  && mkdir -p /var/db \
  && chown app:app /var/db

# install composer dependencies
RUN apt-get update -y \
  && apt-get install -y --no-install-recommends \
  ca-certificates \
  git \
  unzip \
  # cleanup
  && apt autoremove -y \
  && apt clean \
  && rm -rf /var/lib/apt/lists/*

# install composer
COPY --from=composer/composer:2.2-bin /composer /usr/bin/composer

# entrypoint
ENV APP_ENVIRONMENT_MODE="DEVELOPMENT"
COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]

# ports
EXPOSE 80 443

# volumes
VOLUME ["/var/www", "/var/cacana", "/etc/apache2", "/etc/php", "/var/db", "/etc/supervisord.conf"]
