version: '3.7'
services:
  apache2:
    container_name: apache2
    image: relnaggar/rmsy-me-apache2
    init: true
    ports:
      - "80:8080"
      - "443:8443"
    networks:
      - rmsy-me
    volumes:
      - "./apache2/www:/var/www"
      - "./apache2/conf:/etc/apache2"
      - "./apache2/logs:/var/log/apache2"
      - "./apache2/ini:/etc/php/7.3/apache2"
    secrets:
      - rmsy.me.crt
      - rmsy.me.key
      - el-naggar.co.uk.crt
      - el-naggar.co.uk.key
      - elnaggar.co.uk.crt
      - elnaggar.co.uk.key
      - relnaggar.com.crt
      - relnaggar.com.key
      - PGPASSWORD
  postgres:
    container_name: postgres
    image: relnaggar/rmsy-me-postgres
    init: true
    hostname: postgres
    networks:
      - rmsy-me
    volumes:
      - "./postgres/conf:/etc/postgresql/11/main"
      - "./postgres/data:/var/lib/postgresql/11/main"
    secrets:
      - PGPASSWORD
networks:
  rmsy-me:
    name: rmsy-me
