version: '3.7'
services:
  apache2:
    build: ./apache2
  postgres:
    build: ./postgres
secrets:
  rmsy.me.crt:
    file: ./apache2/ssl/localhost.crt
  rmsy.me.key:
    file: ./apache2/ssl/localhost.key
  el-naggar.co.uk.crt:
    file: ./apache2/ssl/localhost.crt
  el-naggar.co.uk.key:
    file: ./apache2/ssl/localhost.key
  elnaggar.co.uk.crt:
    file: ./apache2/ssl/localhost.crt
  elnaggar.co.uk.key:
    file: ./apache2/ssl/localhost.key
  relnaggar.com.crt:
    file: ./apache2/ssl/localhost.crt
  relnaggar.com.key:
    file: ./apache2/ssl/localhost.key
  PGPASSWORD:
    file: ./postgres/PGPASSWORD
