#!/bin/bash
#
# Run all available development tests on development and production builds
#
# Don't allow the push if there are any problems building or running either
# build, or if any test fails
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_NAME="${BASH_SOURCE[0]##*/}"

log_prefix() {
  echo -n "[${SCRIPT_NAME}]: "
}

log() {
  log_prefix
  echo -e "$@"
}

main() {
  log "start"
  
  script/server down
  log "verifying development build:"
  script/server up -b
  script/test
  script/server down

  log "verifying production build:"
  script/server up prod -b
  script/test e2e
  script/server down

  log "end"
}

main "$@"
