#!/bin/bash
#
# Generates private keys (.key) and self-signed certificates (.crt) for a list
# of domains (by default, onlylocalhost)
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

# full directory name of the script, no matter where it is called from
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
readonly SCRIPT_NAME="${0##*/}"
declare -a DOMAINS
readonly DOMAINS=( "localhost" )

usage() {
  err "$(cat <<END
usage: ${SCRIPT_NAME} 
END
  )"
}

# all error messages to STDERR
err() {
  echo "-${SCRIPT_NAME}: $*" >&2
}

main() {
  for domain in "${DOMAINS[@]}"; do
      openssl req -x509 -newkey rsa:4096 -nodes -out "${domain}.crt" -keyout \
        "${domain}.key" -days 825 -sha256 -subj "/CN=${domain}" -extensions \
        EXT -config <( printf \
"[dn]\nCN=${domain}\n[req]\ndistinguished_name=dn\n[EXT]\nsubjectAltName=DNS:${domain}\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth" )
  done
}

main "$@"

