FROM node:20-alpine
WORKDIR /bundler

# install dependencies
COPY package.json .
RUN npm install

# entrypoint
CMD ["npm", "run", "build"]

# copy files for bundling
COPY src/ /bundler/src

# volumes
VOLUME ["/bundler/dist/css"]
