#!/bin/bash
#
# Backup all volumes to a local (.gitignored) directory
#
# inspired by github boilerplate:
# https://github.com/github/scripts-to-rule-them-all
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && \
  pwd)"
. "${SCRIPT_DIR}/lib/shared.sh"

parse_args() {
  # optional
  force=false
  if [[ "${1:-}" == "-f" ]]; then
    force=true
  fi

  log "arguments (\
force: ${force} \
)"
}

main() {
  log start
  cd "${SCRIPT_DIR}/.."
  parse_args "$@"

  # loop through all STACK_VOLUMES
  for volume in "${STACK_VOLUMES[@]}"; do
    if "${force}"; then
      script/backup "${volume}" -f
    else
      script/backup "${volume}"
    fi
  done

  log "end"
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  main "$@"
fi
