#!/bin/bash
#
# Backup Docker-managed volumes to a local (.gitignored) directory
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && \
  pwd)"
. "${SCRIPT_DIR}/lib/shared.sh"

usage() {
  die "$(cat <<END
usage: ${SCRIPT_NAME} volume [-f]
  where volume is a named Docker volume
  where -f forces overwriting previous backup
END
  )"
}

parse_args() {
  volume="${1:-}"

  # required
  if [[ -z "${volume}" ]]; then
    usage
  fi

  # optional
  force=false
  if [[ "${2:-}" == "-f" ]]; then
    force=true
  fi

  # validation
  local valid_volume=false
  for existing_volume in "${STACK_VOLUMES[@]}"; do
    if [[ "${volume}" == "${existing_volume}" ]]; then
      valid_volume=true
      break
    fi
  done

  if ! "${valid_volume}"; then
    die "invalid volume ${volume}"
  fi
  
  log "arguments (\
volume: ${volume} \
force: ${force} \
)"
}

main() {
  log "start" 
  cd "${SCRIPT_DIR}/.."  
  parse_args "$@"  

  if "${force}"; then
    log "forcing overwrite of previous backup"
  else
    while true; do
      log "continue with overwriting previous backup of ${volume}? [y/n]"
      local yn;
      read yn
      case "${yn}" in
          y)
            break
            ;;
          n)
            log "aborting"
            die
            ;;
      esac
    done
  fi

  set +e
    logfun sudo rm -r "backup/${volume}" 2>/dev/null
  set -e

  log "Attempting backup..."
  cat << END |
version: '3.7'
services:
  backup:
    image: debian:10.3-slim
    volumes:
      - "./backup:/backup"
      - "${volume}:/${volume}"
volumes:
  ${volume}:
    external: true
END
  logfun docker-compose -f - run -T --rm backup cp -r "${volume}" backup/
  logfun sudo chmod -R +r "backup/${volume}"

  log "end"
}


if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  main "$@"
fi
