#!/bin/bash
#
# Backup Docker-managed volumes to a local (.gitignored) directory
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && \
  pwd)"
. "${SCRIPT_DIR}/lib/shared"

usage() {
  die "$(cat <<END
usage: ${SCRIPT_NAME} volume
  where volume is a named Docker volume
END
  )"
}

parse_args() {
  volume="${1:-}"

  # required
  if [[ -z "${volume}" ]]; then
    usage
  fi

  # validation
  case "${volume}" in
    db | apache2-logs) ;;
    *) die "invalid volume ${volume}" ;;
  esac
  
  log "arguments (\
volume: ${volume} \
)"
}

main() {
  cd "${SCRIPT_DIR}/.."
  parse_args "$@"
  log "start"

  set +e
    logfun rm -r backup/${volume} 2>/dev/null
  set -e

  log "Attempting backup..."
  cat << END |
version: '3.7'
services:
  backup:
    image: debian:10.3-slim
    volumes:
      - "./backup:/backup"
      - "${volume}:/${volume}"
volumes:
  ${volume}:
END
  logfun docker-compose -f - run --rm backup cp -r "${volume}" backup/

  log "end"
}


if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  main "$@"
fi
