#!/bin/bash
#
# Resolve all dependencies that the application requires to run 
#
# inspired by github boilerplate:
# https://github.com/github/scripts-to-rule-them-all
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && \
  pwd)"
. "${SCRIPT_DIR}/lib/shared.sh"

usage() {
  die "$(cat <<END
usage: ${SCRIPT_NAME} 
END
  )"
}

install_docker() {
  if ! docker --version 2>/dev/null; then
    local unsupported=false;
    case "${OSTYPE}" in
      darwin*) 
        log "installing Docker Desktop for Mac"
        logfun curl https://download.docker.com/mac/stable/Docker.dmg --output \
          Docker.dmg
        logfun hdiutil attach Docker.dmg
        logfun cp -r /Volumes/Docker/Docker.app /Applications
        logfun hdiutil detach /Volumes/Docker
        logfun rm Docker.dmg
        logfun open /Applications/Docker.app/
        ;;
      linux-gnu)
        if [[ "$(uname -r)" =~ *.amzn2.* ]]; then
          log "installing Docker"
          sudo yum update -y
          sudo amazon-linux-extras install docker -y

          # start the docker daemon
          sudo service docker start

          # to allow docker commands to be executed without sudo
          sudo usermod -a -G docker ec2-user  
          
          # make docker auto-start
          sudo chkconfig docker on

          local docker_compose_version="1.25.4"
          log "installing Docker Compose v${docker_compose_version}"
          sudo curl -L "https://github.com/docker/compose/releases/download/\
  ${docker_compose_version}/docker-compose-$(uname -s)-$(uname -m)" \
            -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          log "please reboot with sudo reboot to complete the installation"
        else
          unsupported=true;
        fi
        ;;
      *)
        unsupported=true;
        ;;
    esac
    if [[ "${unsupported}" == true ]]; then
        log "OS ${OSTYPE} not yet supported, please manually install Docker and\
 Docker Compose"
    fi
  fi
}

main() {
  log "start"
  cd "${SCRIPT_DIR}/.."

  install_docker

  log "end"
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  main "$@"
fi
