#!/bin/bash
#
# Launch a console for the applicatio
#
# inspired by github boilerplate:
# https://github.com/github/scripts-to-rule-them-all
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && \
  pwd)"
. "${SCRIPT_DIR}/lib/shared.sh"

usage() {
  die "$(cat <<END
usage: ${SCRIPT_NAME} service [--root] [command]
  where service is a service name in the docker-compose.yml file
  where --root is an optional flag to run as root
  where command is an optional command to run in the service (default: bash)
END
  )"
}

parse_args() {
  # required
  service="${1:-}"
  if [[ -z "${service}" ]]; then
    usage
  fi
  shift
  log "${service}"
  
  # optional with validation
  root="${1:-}"  
  if [[ "${root}" == "--root" ]]; then
    root=("-u" "root")
    shift
  else
    root=()
  fi

  # optional
  it="-it"
  T=""
  command="${1:-}"
  if [[ -n "${command}" ]]; then
    command=("-c" "${command}")
    it=""
    T="-T"
  fi 

  log "arguments (\
service: ${service}, \
root: ${root:-}, \
command: ${command} \
)"
}

main() {
  log "start"
  cd "${SCRIPT_DIR}/.."
  parse_args "$@"

  if is_stack_up; then
    local container="$( \
      docker ps -a \
      | grep -o "${STACK_NAME}_${service}.*" \
      | head -1 \
    )"
    logfun docker exec ${it} ${root[@]:-} "${container}" bash ${command[@]:-}
  elif is_compose_up; then
    logfun docker-compose exec ${T} ${root[@]:-} "${service}" bash ${command[@]:-}
  else
    die "the server is not running"
  fi

  log "end"
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  main "$@"
fi
