#!/bin/bash
#
# Recreate the database and run migrations
#
# inspired by github boilerplate:
# https://github.com/github/scripts-to-rule-them-all
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && \
  pwd)"
. "${SCRIPT_DIR}/lib/shared.sh"

parse_args() {
  # optional
  force=false
  if [[ "${1:-}" == "-f" ]]; then
    force=true
  fi

  log "arguments (\
force: ${force} \
)"
}

main() {
  log start
  cd "${SCRIPT_DIR}/.."
  parse_args "$@"

  script/server down
  logfun docker container prune -f
  # if "${force}"; then
  #   script/backupall -f
  # else 
  #   script/backupall
  # fi  
  set +e
    logfun docker volume rm db
    logfun docker volume rm django-media
  set -e
  logfun docker volume create db
  logfun docker volume create django-media

  log "end"
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  main "$@"
fi
