#!/bin/bash
#
# Django createsuperuser
#
# inspired by github boilerplate:
# https://github.com/github/scripts-to-rule-them-all
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && \
  pwd)"
. "${SCRIPT_DIR}/lib/shared.sh"

usage() {
  die "$(cat <<END
usage: ${SCRIPT_NAME} [-d | password]
  where -d is a flag to use the default password
  you must provide a password if you do not use the -d flag
END
  )"
}

parse_args() {
  # required arguments
  arg="${1:-}"
  if [[ -z "${arg}" ]]; then
    usage
  fi

  log "arguments (\
arg: ${arg}, \
)"
}

main() {
  log start
  cd "${SCRIPT_DIR}/.."
  parse_args "$@"
  
  # if arg is -d, then use default password
  # otherwise, use the arg as the password
  if [[ "${arg}" == "-d" ]]; then
    local password="m2y74EAt26dz5t#W"
  else
    local password="${arg}"
  fi

  script/dbmigrate
  script/console apache2 "cd /var/www/autojobgpt-django/ && export && export DJANGO_SUPERUSER_PASSWORD="${password}" && python3 manage.py createsuperuser --no-input --username root --email rmsy@rmsy.me"

  log "end"
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  main "$@"
fi
