#!/bin/bash
#
# Copy default directories (e.g. config files) from a newly started container
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && \
  pwd)"
. "${SCRIPT_DIR}/lib/shared.sh"

usage() {
  die "$(cat <<END
usage: ${SCRIPT_NAME} host_directory
  host_directory must contain a shell script named .defaults-info that exports:
  SERVICE   the name of the service from which the defaults will be copied
  SRC       the container path to the directory containing the defaults
END
  )"
}

main() {
  log "start"
  cd "${SCRIPT_DIR}/.."

  # parse command line arguments
  local host_directory="${1:-}"

  # always required
  if [[ -z "${host_directory}" ]]; then
    usage
  fi

  logfun cd ${host_directory}
  local file_to_source=".defaults-info"
  if [[ ! -f "${file_to_source}" ]]; then
    err "${file_to_source}: file not found"
    exit 1
  fi
  logfun . "${file_to_source}"

  set +e
    rm -r "defaults" 2>/dev/null
  set -e
  logfun mkdir "defaults"

  # just in case it's running, stop the service
  set +e
    logfun docker stop "default-${SERVICE}"
    logfun docker rm "default-${SERVICE}"
  set -e

  logfun docker run -d --name "default-${SERVICE}" \
    "${STACK_NAME}-${SERVICE}"

  logfun docker cp "default-${SERVICE}:${SRC}/." defaults

  logfun docker stop "default-${SERVICE}" 

  # cleanup just in case
  logfun unset SERVICE
  logfun unset SOURCE

  log "end"
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  main "$@"
fi
