#!/bin/bash
#
# Collate all available logging information from all services
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && \
  pwd)"
. "${SCRIPT_DIR}/lib/shared.sh"

usage() {
  die "$(cat <<END
usage: ${SCRIPT_NAME}
END
  )"
}

main() {
  log "start"
  cd "${SCRIPT_DIR}/.."

  for service in "${STACK_SERVICES[@]}"; do
    log "foreground logs for ${service}:"

    if is_stack_up; then
      logfun docker service logs "${STACK_NAME}_${service}"
    elif is_compose_up; then
      logfun docker-compose logs "${service}"
    fi

    set +e
      script/backup "${service}-logs" 2>/dev/null
      log "log files for ${service}:"
      cat "backup/${service}-logs/"*".log" 2>/dev/null
      local result="$?"
    set -e
    if [[ "$result" -ne 0 ]]; then
      set +e
        sudo cat "backup/${service}-logs/"*".log" 2>/dev/null
      set -e
    fi
  done

  log "end"
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  main "$@"
fi
