#!/bin/bash
#
# Launch the application and any extra required processes locally
#
# inspired by github boilerplate:
# https://github.com/github/scripts-to-rule-them-all
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && \
  pwd)"
. "${SCRIPT_DIR}/lib/shared.sh"

usage() {
  die "$(cat <<END
usage: ${SCRIPT_NAME} down | up|restart [environment] [build]

environment can be:
  -d    development, default
  -s    staging
  -p    production

build can be:
  dev   development, default for development environment
  prod  production, mandatory for staging/production environments
END
  )"
}

parse_args() {
  # required arguments
  cmd="${1:-}"
  if [[ -z "${cmd}" ]]; then
    usage
  fi
  shift

  # optional arguments
  environment=""
  build=""
  while (( $# > 0 )); do
    local arg="${1:-}"
    case "${arg}" in
      -d | -p | -s)
        if [[ -z "${environment}" ]]; then
          environment="${arg}"
        else
          usage
        fi
        ;;
      dev | prod)
        if [[ -z "${build}" ]]; then
          build="${arg}"
        else
          usage
        fi
        ;;
      *)
        usage
        ;;
    esac
    shift
  done

  # defaults
  if [[ -z "${environment}" ]]; then
    environment=-d
  fi
  if [[ -z "${build}" ]]; then
    build=dev
  fi

  log "arguments (\
cmd: ${cmd}, \
environment: ${environment}, \
build: ${build}\
)"
}

main() {
  log "start"
  cd "${SCRIPT_DIR}/.."
  parse_args "$@"

  case "${cmd}" in
    up)
      case "${environment}" in
        -d)
          script/build "${build}"
          logfun docker-compose \
            -f docker-compose.yml \
            -f "build/docker-compose.${build}.yml" \
            -f build/docker-compose.dev.secrets.yml \
            up -d
          ;;
        -s)
          if [[ "${build}" == "dev" ]]; then
            log "warning: ignoring build option and using production image" \
              "anyway"
          fi
          logfun docker stack deploy \
            -c docker-compose.yml \
            -c build/docker-compose.prod.yml \
            -c build/docker-compose.stage.secrets.yml \
            "${STACK_NAME}"
          ;;
        -p)
          if [[ "${build}" == "dev" ]]; then
            echo "warning: ignoring build option and using production image" \
              "anyway"
          fi
          logfun sudo docker stack deploy \
            -c docker-compose.yml \
            -c build/docker-compose.prod.yml \
            -c build/docker-compose.prod.secrets.yml \
           "${STACK_NAME}"
          ;;
      esac
      ;;
    down)
      logfun docker stack rm ${STACK_NAME}
      sleep 3
      logfun  docker-compose \
        -f docker-compose.yml \
        -f build/docker-compose.dev.yml down
      ;;
    restart)
      script/server down
      script/server up "${environment}" "${build}"
      ;;
    *)
      usage
      ;;
  esac

  log "end"
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  main "$@"
fi
