#!/bin/bash
#
# Launch the application and any extra required processes locally
#
# inspired by github boilerplate:
# https://github.com/github/scripts-to-rule-them-all
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && \
  pwd)"
. "${SCRIPT_DIR}/lib/shared.sh"

usage() {
  die "$(cat <<END
usage: ${SCRIPT_NAME} down | up [environment] [build] [ground]

environment can be:
  -d    development, default
  -s    staging
  -p    production

build can be:
  dev   development, default for development environment
  prod  production, mandatory for staging/production environments

ground can be:
  -b  background, mandatory for staging/production environments
  -f  foreground, default for development environment
END
  )"
}

parse_args() {
  # required arguments
  cmd="${1:-}"
  if [[ -z "${cmd}" ]]; then
    usage
  fi
  shift

  # optional arguments
  environment=""
  build=""
  ground=""
  while (( $# > 0 )); do
    local arg="${1:-}"
    case "${arg}" in
      -d | -p | -s)
        if [[ -z "${environment}" ]]; then
          environment="${arg}"
        else
          usage
        fi
        ;;
      dev | prod)
        if [[ -z "${build}" ]]; then
          build="${arg}"
        else
          usage
        fi
        ;;
      -b | -f)
        if [[ -z "${ground}" ]]; then
          ground="${arg}"
        else
          usage
        fi
        ;;
      *)
        usage
        ;;
    esac
    shift
  done

  # defaults
  if [[ -z "${environment}" ]]; then
    environment=-d
  fi
  if [[ -z "${build}" ]]; then
    case "${environment}" in 
      -d) build=dev ;;
      -s|-p) build=prod ;;
    esac
  fi
  # if [[ -z "${ground}" ]]; then
  #   case "${environment}" in
  #     -d) ground=-f ;;
  #     -s|-p) ground=-b ;;
  #   esac
  # fi
  ground=-b

  log "arguments (\
cmd: ${cmd}, \
environment: ${environment}, \
build: ${build}, \
ground: ${ground}\
)"
}

compose_down() {
  if is_compose_up; then
    logfun docker-compose down
  fi
}

main() {
  log "start"
  cd "${SCRIPT_DIR}/.."
  parse_args "$@"

  case "${cmd}" in
    up)
      case "${environment}" in
        -d)
          script/server down
          script/build "${build}"

          if [[ "${ground}" == "-b" ]]; then
            local end=-d
          fi
          
          case "${build}" in
            dev)
              set +e
                logfun docker-compose \
                  -f docker-compose.yml \
                  -f docker-compose.override.yml \
                  -f build/docker-compose.dev.secrets.yml \
                  up ${end:-}
                result="$?"
              set -e
              ;;
            *)
              set +e
                logfun docker-compose \
                  -f docker-compose.yml \
                  -f build/docker-compose.prod.yml \
                  -f build/docker-compose.dev.secrets.yml \
                  up ${end:-}
                result="$?"
              set -e
              ;;
          esac
          if [[ "${result}" -eq 1 ]]; then
            die "error starting: have you run the setup script?"
          fi
          ;;
        -s)
          if [[ "${build}" == "dev" ]]; then
            log "warning: ignoring build option and using production image" \
              "anyway"
          fi
          compose_down
          logfun docker stack deploy \
            -c docker-compose.yml \
            -c build/docker-compose.prod.yml \
            -c build/docker-compose.stage.secrets.yml \
            "${STACK_NAME}"
          ;;
        -p)
          if [[ "${build}" == "dev" ]]; then
            log "warning: ignoring build option and using production image" \
              "anyway"
          fi
          compose_down
          logfun sudo docker stack deploy \
            -c docker-compose.yml \
            -c build/docker-compose.prod.yml \
            -c build/docker-compose.prod.secrets.yml \
           "${STACK_NAME}"
          ;;
      esac
      ;;
    down)
      logfun docker stack rm ${STACK_NAME}
      compose_down
      ;;
    *)
      usage
      ;;
  esac

  log "end"
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  main "$@"
fi
