#!/bin/bash
#
# Set up the application for the first time after cloning, or set it back to the
# initial first unused state
#
# using github boilerplate:
# https://github.com/github/scripts-to-rule-them-all
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && \
  pwd)"
. "${SCRIPT_DIR}/lib/shared.sh"

usage() {
  die "$(cat <<END
usage: ${SCRIPT_NAME} 
END
  )"
}

generate_self_signed_certificates() {
  domain="${1:-}"
  dir="${2:-}"
  logfun openssl req -x509 -newkey rsa:4096 -nodes -out "${dir}/${domain}.crt" \
    -keyout "${dir}/${domain}.key" -days 825 -sha256 -subj "/CN=localhost" \
    -extensions EXT -config <( cat<<END
[dn]
CN=localhost
[req]
distinguished_name=dn
[EXT]
subjectAltName=DNS:localhost
keyUsage=digitalSignature
extendedKeyUsage=serverAuth
END
    )
}

setup_secrets() {
  local secrets_dir=secrets
  set +e
    mkdir "$secrets_dir" 2>/dev/null
  set -e
  echo "password" > "$secrets_dir"/PGPASSWORD

  case "$OSTYPE" in
    darwin*) 
      log "removing old localhost certificates from Keychain..."
      logfun sudo security delete-certificate -c localhost
      log "...success"
      ;;
  esac

  for domain in "${STACK_DOMAINS[@]}"; do
    generate_self_signed_certificates "$domain" "$secrets_dir"
  done

  case "$OSTYPE" in
    darwin*) 
      log "adding self-signed localhost certificates to Keychain..."
      logfun sudo security add-trusted-cert -d -r trustRoot \
        -k /Library/Keychains/System.keychain secrets/rmsy.me.crt
      log "...success"
      ;;
    *)
      log "warning: SSL certificates remain untrusted"
  esac
}

create_volumes() {
  for volume in "${STACK_VOLUMES[@]}"; do
    logfun docker volume create "${volume}"
  done
}

symlink_githooks() {
  logfun rm -r .git/hooks
  logfun ln -vs ../githooks/ .git/hooks
}

initialise_swarm() {
  set +e
    logfun script/server down
    logfun docker swarm init
  set -e
}

main() {
  log "start"
  cd "${SCRIPT_DIR}/.."

  initialise_swarm
  symlink_githooks
  create_volumes
  setup_secrets

  log "end"
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  main "$@"
fi
