#!/bin/bash
#
# TODO
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && \
  pwd)"
. "${SCRIPT_DIR}/lib/shared.sh"

usage() {
  die"$(cat <<END
usage: ${SCRIPT_NAME} 
END
  )"
}

main() {
  log "starting"
  cd "${SCRIPT_DIR}/.."
  
  log "development status:"
  docker-compose \
    -f docker-compose.yml \
    -f build/docker-compose.dev.yml \
    images
  docker-compose \
    -f docker-compose.yml \
    -f build/docker-compose.dev.yml \
    ps
  docker-compose \
    -f docker-compose.yml \
    -f build/docker-compose.dev.yml \
    top
  
  log "staging/production status:"
  docker stack ps "${STACK_NAME}"

  log "end"
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  main "$@"
fi
