#!/bin/bash
#
# Run test suite on the running application
#
# using github boilerplate:
# https://github.com/github/scripts-to-rule-them-all
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && \
  pwd)"
. "${SCRIPT_DIR}/lib/shared.sh"

usage() {
  die "$(cat <<END
usage: ${SCRIPT_NAME} [tests] ...

tests can be:
  unit  all PHPUnit tests (on the locally running application)
  e2e   all Cucumber tests (on the locally running application)
  live  all Cucumber tests (on the live application)
the default is to run all available local tests

unit tests are not available for the production build
END
  )"
}

parse_args() {
  # defaults
  if [[ $# -eq 0 ]]; then
    if is_compose_up; then
      tests=("unit" "e2e")
    else
      tests=("e2e")
    fi
  else
    tests=("$@")
  fi

  log "arguments (\
tests: ${tests[@]}\
)" 
}

main() {
  log "start"
  cd "${SCRIPT_DIR}/.."
  parse_args "$@"

  if ! is_server_up; then
    err "no server running"
    exit 1
  fi

  local success=0
  for t in "${tests[@]}"; do
    case "${t}" in
      unit) 
        log "running unit tests:"
        set +e
          logfun apache2/www/tests/unit
          local result="$?"
        set -e
        if [[ "${result}" -eq 127 ]]; then
          log "unit tests not available (are you using the production build?)"
        elif [[ "${result}" -ne 0 ]]; then
          exit "${result}"
        fi
        ;;
      e2e)
        log "running local end-to-end tests:"
        cd selenium
        logfun docker-compose down
        logfun docker-compose run -d \
          -e FILE_NAME="chrome_localhost__$(date '+%Y_%m_%d__%H_%M_%S').mp4" \
          selenium-chrome-video
        set +e
          logfun docker-compose run cucumber
          local result="$?"
        set -e
        logfun docker-compose down
        if [[ "${result}" -ne 0 ]]; then
          exit "${result}"
        fi
        ;;
      live)
        log "running live end-to-end tests:"
        cd selenium
        logfun docker-compose down
        logfun docker-compose run -d \
          -e FILE_NAME="chrome_live__$(date '+%Y_%m_%d__%H_%M_%S').mp4" \
          selenium-chrome-video
        set +e
          logfun docker-compose run cucumber cucumber https://rmsy.me
          local result="$?"
        set -e
        logfun docker-compose down
        if [[ "${result}" -ne 0 ]]; then
          exit "${result}"
        fi
        ;;
      *)
        usage
    esac
  done
  log "success"
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  main "$@"
fi
