#!/bin/bash
#
# Run test suite on the running application
#
# using github boilerplate:
# https://github.com/github/scripts-to-rule-them-all
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && \
  pwd)"
. "${SCRIPT_DIR}/lib/shared"

usage() {
  die "$(cat <<END
usage: ${SCRIPT_NAME} [tests] ...

tests can be:
  unit  all PHPUnit tests
  e2e   not implemented yet
the default is to run all available tests

unit tests are not available for the production build
END
  )"
}

parse_args() {
  # defaults
  if [[ $# -eq 0 ]]; then
    tests=("unit" "e2e")
  else
    tests=("$@")
  fi

  log "arguments (\
tests: ${tests[@]}\
)" 
}

main() {
  log "start"
  cd "${SCRIPT_DIR}/.."
  parse_args "$@"

  if ! is_server_up; then
    err "no server running"
    exit 1
  fi

  for t in "${tests[@]}"; do
    case "${t}" in
      unit) 
        log "running unit tests:"
        set +e
          apache2/www/tests/unit
          result="$?"
        set -e
        if [[ "${result}" -eq 127 ]]; then
          log "unit tests not available (are you using the production build?)"
        fi
        ;;
      e2e)
        log "running end-to-end tests:"
        log "no end-to-end tests yet"
        ;;
      *)
        usage
    esac
  done
  log "end"
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  main "$@"
fi
