#!/bin/bash
#
# Watch Django source files for changes and restart server
#
# inspired by github boilerplate:
# https://github.com/github/scripts-to-rule-them-all
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && \
  pwd)"
. "${SCRIPT_DIR}/lib/shared.sh"

main() {
  log start
  cd "${SCRIPT_DIR}/.."
  
  fswatch -o -r apache2/www/autojobgpt-django | (while read; do script/server up; done)

  log "end"
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  main "$@"
fi
