#!/bin/bash
#
# Entrypoint for relnaggar/rmsy-me-postgres
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

main() {
  local cmd=${1:-}

  if [[ "${cmd}" == "postgres" ]]; then
    chmod 700 "${PGDATA}"

    # running internally first to configure
    pg_ctl start -o \
      "--config-file=${PGCONF}/postgresql.conf --listen_addresses=''"
    psql -c \
      "alter user postgres with password '$(cat /run/secrets/PGPASSWORD)';"
    pg_ctl stop

    # running externally
    exec postgres "--config-file=${PGCONF}/postgresql.conf"
  else
    exec "$@"
  fi
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  main "$@"
fi
