#!/bin/bash

# local setup:
# brew install selenium-server-standalone
# brew install --cask chromedriver
# https://stackoverflow.com/questions/21369953/need-help-installing-junit-on-mac-how-to-add-junit-to-path-environmental-variabl/26977630

CLASSPATH=.:/usr/local/Cellar/selenium-server-standalone/3.141.59_2/libexec/selenium-server-standalone-3.141.59.jar
CLASSPATH="${CLASSPATH}":~/java/junit-4.13.1.jar:~/java/hamcrest-core-1.3.jar

echo "let g:syntastic_java_javac_classpath = '${CLASSPATH}'" > \
  .syntastic_javac_config
javac -cp "${CLASSPATH}" *.java
export TEST_URL="https://rmsy.me"
java -cp "${CLASSPATH}" org.junit.runner.JUnitCore JunitSeleniumTest
export TEST_URL="https://localhost"
java -cp "${CLASSPATH}" org.junit.runner.JUnitCore JunitSeleniumTest
