# Generated by Django 4.2.4 on 2023-08-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(blank=True, max_length=26)),
                ('company', models.CharField(blank=True, max_length=26)),
                ('text', models.TextField(blank=True)),
                ('chat_messages', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('upload', models.FileField(upload_to='templates/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.UniqueConstraint(fields=('title', 'company'), name='unique_title_company'),
        ),
    ]
