# Generated by Django 4.2.6 on 2023-10-31 12:28

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FillField',
            fields=[
                ('key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('data_type', models.CharField(max_length=7)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(blank=True, max_length=26)),
                ('company', models.CharField(blank=True, max_length=26)),
                ('text', models.TextField(blank=True)),
                ('chat_messages', models.JSONField(blank=True, null=True)),
                ('date_applied', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=26)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('docx', models.FileField(upload_to='resumes/')),
                ('png', models.FileField(upload_to='resumes/')),
                ('chat_messages', models.JSONField(blank=True, null=True)),
            ],
            bases=(models.Model, app.models.IDocumentModel),
        ),
        migrations.CreateModel(
            name='ResumeSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docx', models.FileField(upload_to='templates/')),
                ('png', models.FileField(upload_to='templates/')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            bases=(models.Model, app.models.IDocumentModel),
        ),
        migrations.AddConstraint(
            model_name='resumetemplate',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
        migrations.AddField(
            model_name='resumesubstitution',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='app.resume'),
        ),
        migrations.AddField(
            model_name='resume',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='app.job'),
        ),
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.resumetemplate'),
        ),
        migrations.AddField(
            model_name='job',
            name='chosen_resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_jobs', to='app.resume'),
        ),
        migrations.AddConstraint(
            model_name='resumesubstitution',
            constraint=models.UniqueConstraint(fields=('resume', 'key', 'value'), name='unique_resume_key_value'),
        ),
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.UniqueConstraint(fields=('job', 'version'), name='unique_job_version'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('title', 'company'), name='unique_title_company'),
        ),
    ]
