# Generated by Django 4.2.4 on 2023-08-22 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(blank=True, max_length=26)),
                ('company', models.CharField(blank=True, max_length=26)),
                ('text', models.TextField(blank=True)),
                ('chat_messages', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='resumes/')),
                ('chat_messages', models.JSONField(blank=True, null=True)),
                ('job_posting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeFillField',
            fields=[
                ('key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('data_type', models.CharField(max_length=7)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('upload', models.FileField(upload_to='templates/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('chat_messages', models.JSONField(blank=True, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='app.resume')),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.resumetemplate'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.UniqueConstraint(fields=('title', 'company'), name='unique_title_company'),
        ),
        migrations.AddConstraint(
            model_name='resumesubstitution',
            constraint=models.UniqueConstraint(fields=('resume', 'key', 'value', 'version'), name='unique_resume_key_value_version'),
        ),
    ]
