# Generated by Django 4.2.4 on 2023-08-21 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='resumes/')),
                ('job_posting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.jobposting')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.resumetemplate')),
            ],
        ),
    ]
