# Generated by Django 4.2.6 on 2023-10-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_upload_resume_docx_resumetemplate_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumetemplate',
            old_name='pdf',
            new_name='png',
        ),
    ]
