# Generated by Django 4.2.6 on 2023-10-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_pdf_resumetemplate_png'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumetemplate',
            name='png',
            field=models.FileField(upload_to='templates/'),
        ),
    ]
