# Generated by Django 4.2.6 on 2023-10-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_resumetemplate_png'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='resume_template',
        ),
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.resumetemplate'),
        ),
    ]
