#!/bin/bash
#
# Entrypoint for relnaggar/rmsy-me-cucumber
#
# using Google Shell Style Guide:
# https://google.github.io/styleguide/shellguide.html
#
# using bash strict mode:
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

main() {
  local cmd=${1:-}
  local GRADLE_DIR=/home/gradle

  if [[ "${cmd}" == "cucumber" ]]; then
    local test_url=${2:-}
    cd "${GRADLE_DIR}"
    export TEST_URL="${test_url}"
    gradle cucumber
  elif [[ "${cmd}" == "webdriver" ]]; then
    cd "${GRADLE_DIR}"
    gradle run
  else
    exec "$@"
  fi
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  main "$@"
fi
