version: '3.7'
services:
  selenium-chrome:
    container_name: selenium-chrome
    image: selenium/standalone-chrome:4.0.0-beta-1-20210215
    ports:
      - "4444:4444"
      - "6900:5900"
    networks:
      - selenium
    volumes:
      - "/dev/shm:/dev/shm"
      - "./downloads:/home/seluser/Downloads"
  selenium-chrome-video:
    image: selenium/video:ffmpeg-4.3.1-20210215
    depends_on:
      - selenium-chrome
    networks:
      - selenium
    volumes:
      - "./videos:/videos"
    environment:
      - DISPLAY_CONTAINER_NAME=selenium-chrome
  cucumber:
    container_name: cucumber
    image: rmsy-me-cucumber
    build:
      context: "."
      args:
        GRADLE_PROJECT: cucumber
    volumes:
      - "./cucumber/java:/home/gradle/java"
      - "./cucumber/features:/home/gradle/features"
      - "./cucumber/src:/home/gradle/src"
    command: ["cucumber", "https://host.docker.internal"]
    depends_on:
      - selenium-chrome
    networks:
      - selenium
  webdriver:
    container_name: webdriver
    image: rmsy-me-webdriver
    build:
      context: "."
      args:
        GRADLE_PROJECT: webdriver
    volumes:
      - "./webdriver/java:/home/gradle/java"
    command: ["webdriver"]
    depends_on:
      - selenium-chrome
    networks:
      - selenium
networks:
  selenium:
    name: selenium
